#!/bin/bash

function clean_exit() {
	pkill webserv > /dev/null 2>&1
	make fclean
	if [ $1 -eq 1 ]
	then
		echo "FAILED"
	 else
		echo "OK"
	fi
	exit $1
}

function assert() {
	if !($1)
	then
		[[ -n "$2" ]] && echo $2
		clean_exit 1
	fi
}

trap "clean_exit 1" SIGHUP SIGINT SIGTERM
remote="$1"
url="$2"

assert "which python3" "please install python3"
assert "which php-cgi" "please install php-cgi"

make re config
./webserv ./conf/webserv.conf > /dev/null 2>&1 &

sleep 1

assert "pgrep webserv"
assert "python3 ./tests/test.py"

pkill webserv > /dev/null 2>&1
./webserv ./conf/webserv_cmp.conf > /dev/null 2>&1 &

sleep 1
assert "pgrep webserv"
assert "python3 tests/compare_test/compare_test.py webserv"

pkill webserv > /dev/null 2>&1
./webserv ./conf/multi_name.conf > /dev/null 2>&1 &

sleep 1
assert "tests/multi_name.sh"

clean_exit 0
